# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Blog.create title: "Jonas Neubauer, otra vez campeón", thumbnail: "jonasCampeonCTWC2017.jpg", description: "Jonas Neubauer sigue dominando la escena competitiva de Tetris clásico. El estadounidense gana por séptima vez el Classic Tetris World Championship, donde sólo ha sido derrotado una vez en la historia del campeonato.", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet est id enim accumsan tristique. Nam pretium tincidunt nisl, a accumsan dui pretium quis. Proin est massa, euismod fermentum ullamcorper at, efficitur sit amet dolor. Aliquam id lorem vulputate, varius massa vitae, facilisis nisl. Integer consequat massa varius velit egestas, at mattis est mollis. Aliquam lacinia nisl est, id tincidunt libero interdum vitae. Mauris varius libero vel tempor feugiat.<br><br>Ut non nulla neque. Phasellus libero diam, vestibulum vel dui ac, porttitor sollicitudin justo. Aliquam ullamcorper enim neque, at luctus urna sollicitudin a. In sed felis lacus. In tincidunt purus quis orci lobortis, non interdum diam rutrum. Pellentesque rhoncus dictum magna at convallis. Aliquam erat volutpat. Morbi lobortis efficitur feugiat. Phasellus aliquet orci eros, vitae aliquet eros tristique sit amet. Vivamus consequat tellus dui. Pellentesque scelerisque nunc a viverra aliquam. Cras id condimentum neque. Aliquam non efficitur ligula, eget vehicula mi."

Blog.create title: "La tierra no es esférica, es un Tetris clásico", thumbnail: "mundoTetris.jpg", description: "Y esto no es un clickbait, para nada.", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet est id enim accumsan tristique. Nam pretium tincidunt nisl, a accumsan dui pretium quis. Proin est massa, euismod fermentum ullamcorper at, efficitur sit amet dolor. Aliquam id lorem vulputate, varius massa vitae, facilisis nisl. Integer consequat massa varius velit egestas, at mattis est mollis. Aliquam lacinia nisl est, id tincidunt libero interdum vitae. Mauris varius libero vel tempor feugiat.<br><br>Ut non nulla neque. Phasellus libero diam, vestibulum vel dui ac, porttitor sollicitudin justo. Aliquam ullamcorper enim neque, at luctus urna sollicitudin a. In sed felis lacus. In tincidunt purus quis orci lobortis, non interdum diam rutrum. Pellentesque rhoncus dictum magna at convallis. Aliquam erat volutpat. Morbi lobortis efficitur feugiat. Phasellus aliquet orci eros, vitae aliquet eros tristique sit amet. Vivamus consequat tellus dui. Pellentesque scelerisque nunc a viverra aliquam. Cras id condimentum neque. Aliquam non efficitur ligula, eget vehicula mi."

Blog.create title: "Tetris sigue siendo el juego más vendido", thumbnail: "tetrisTopVentas.jpg", description: "Minecraft le pisa los talones en el puesto, pero en 2018 Tetris sigue en cabeza. Analizamos qué otros juegos amenazan al lider con quitarle su puesto.", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet est id enim accumsan tristique. Nam pretium tincidunt nisl, a accumsan dui pretium quis. Proin est massa, euismod fermentum ullamcorper at, efficitur sit amet dolor. Aliquam id lorem vulputate, varius massa vitae, facilisis nisl. Integer consequat massa varius velit egestas, at mattis est mollis. Aliquam lacinia nisl est, id tincidunt libero interdum vitae. Mauris varius libero vel tempor feugiat.<br><br>Ut non nulla neque. Phasellus libero diam, vestibulum vel dui ac, porttitor sollicitudin justo. Aliquam ullamcorper enim neque, at luctus urna sollicitudin a. In sed felis lacus. In tincidunt purus quis orci lobortis, non interdum diam rutrum. Pellentesque rhoncus dictum magna at convallis. Aliquam erat volutpat. Morbi lobortis efficitur feugiat. Phasellus aliquet orci eros, vitae aliquet eros tristique sit amet. Vivamus consequat tellus dui. Pellentesque scelerisque nunc a viverra aliquam. Cras id condimentum neque. Aliquam non efficitur ligula, eget vehicula mi."

Blog.create title: "¿Tetrominós fantasma para jugadores nuevos?", thumbnail: "TetrisGhost.jpg", description: "Analizamos hasta qué punto los tetrominós fantasmas (aquellos que indican dónde va a caer el actual) son buenos para los jugadores novatos.", text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam imperdiet est id enim accumsan tristique. Nam pretium tincidunt nisl, a accumsan dui pretium quis. Proin est massa, euismod fermentum ullamcorper at, efficitur sit amet dolor. Aliquam id lorem vulputate, varius massa vitae, facilisis nisl. Integer consequat massa varius velit egestas, at mattis est mollis. Aliquam lacinia nisl est, id tincidunt libero interdum vitae. Mauris varius libero vel tempor feugiat.<br><br>Ut non nulla neque. Phasellus libero diam, vestibulum vel dui ac, porttitor sollicitudin justo. Aliquam ullamcorper enim neque, at luctus urna sollicitudin a. In sed felis lacus. In tincidunt purus quis orci lobortis, non interdum diam rutrum. Pellentesque rhoncus dictum magna at convallis. Aliquam erat volutpat. Morbi lobortis efficitur feugiat. Phasellus aliquet orci eros, vitae aliquet eros tristique sit amet. Vivamus consequat tellus dui. Pellentesque scelerisque nunc a viverra aliquam. Cras id condimentum neque. Aliquam non efficitur ligula, eget vehicula mi."

Blog.create title: "¿No sabes como mejorar en las partidas?", thumbnail: "JavierSanchezVillar.jpg", description: "El alimento de los campeones" , text: "Come bocadillos. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec consectetur ex nec scelerisque elementum. Aenean tempus velit consectetur elit consectetur ullamcorper. Maecenas eu tortor nec velit maximus porta. Nam iaculis finibus semper. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed commodo vel augue ac gravida. Fusce id tincidunt dui. Sed vel mauris sed nisi gravida sodales. Duis facilisis eros eros, eu lobortis ligula condimentum vel. Integer posuere sapien ante, non elementum tortor pellentesque at. In hac habitasse platea dictumst. Vestibulum commodo sapien purus, non blandit diam pulvinar at. Maecenas in suscipit nulla. Suspendisse sodales faucibus rhoncus. Mauris libero orci, bibendum non viverra in, accumsan at sem. Etiam sit amet quam dignissim, laoreet diam eu, dignissim nisl. Cras eget ligula id risus ornare aliquet. Nullam nunc tortor, blandit tempus accumsan sed, pellentesque in sapien. Proin feugiat, odio nec posuere malesuada, odio ipsum ornare dui, at semper. "